name: pull_request-check

on: [pull_request]

# 同一PRに連続pushしたとき、前の実行をキャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Danger JS
        # usesがエラーになるissues解決待ち
        # https://github.com/github/vscode-github-actions/issues/143
        uses: danger/danger-js@11.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
